# int
DIAS_TOTALES_TORNEO = 10
# str
ARENA_INICIAL = 'mojada'
# int
CANTIDAD_EXCAVADORES_INICIALES = 4
# float
METROS_META = 100.0
# float
PROB_ENCONTRAR_ITEM = 0.6
# float
PROB_ENCONTRAR_TESORO = 0.3
# float
PROB_ENCONTRAR_CONSUMIBLE = 0.7
# float
PROB_INICIAR_EVENTO = 0.4
# float
PROB_LLUVIA = 0.4
# float
PROB_TERREMOTO = 0.3
# float
PROB_DERRUMBE = 0.3
# float
METROS_PERDIDOS_DERRUMBE = 20.0
# int
FELICIDAD_PERDIDA = 4
# float
POND_ARENA_NORMAL = 0.2
# int
FELICIDAD_ADICIONAL_DOCENCIO = 15
# int
FUERZA_ADICIONAL_DOCENCIO = 25
# int
ENERGIA_PERDIDA_DOCENCIO = 34
# int
ENERGIA_ADICIONAL_TAREO = 10
# int
SUERTE_ADICIONAL_TAREO = 20
# int
EDAD_ADICIONAL_TAREO = 40
# int
FELICIDAD_PERDIDA_TAREO = 5
