# from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import (QWidget, QLabel, QApplication, QHBoxLayout,
                             QVBoxLayout, QPushButton, QGridLayout, QLineEdit)
from PyQt5.QtGui import QFont, QPixmap, QIcon
import os
import json
import sys


class VentanaJuego(QWidget):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        with open(os.path.join('parametros.json')) as archivo:
            self.parametros = json.load(archivo)
        self.init__gui()

    def init__gui(self):
        self.setGeometry(300, 200, 1280, 720)
        self.setWindowTitle('Ventana de Juego')
        self.setFixedSize(1280, 720)
        ruta_icono = os.path.join(*self.parametros["RUTA_ICONO"])
        self.setWindowIcon(QIcon(ruta_icono))
        ruta_fondo = os.path.join(*self.parametros["RUTA_FONDO_JUEGO"])
        self.fondo = QLabel(self)
        self.fondo.setPixmap(QPixmap(ruta_fondo))
        self.fondo.setFixedSize(1280, 720)
        self.fondo.setScaledContents(True)
        self.layout_general = QVBoxLayout()
        self.layout_general.addSpacing(25)
        font = QFont('Arial', 11)
        font.setBold(True)
        self.primer_layout = QHBoxLayout()
        self.numero_mayor = QLabel('Numero mayor anunciado: x', self)
        self.numero_mayor.setStyleSheet("color: white;")
        self.numero_mayor.setFont(font)
        self.turno_anterior = QLabel('Turno anterior fue: Jugador------', self)
        self.turno_anterior.setStyleSheet("color: white;")
        self.turno_anterior.setFont(font)
        self.n_turno = QLabel('Numero turno: x', self)
        self.n_turno.setStyleSheet("color: white;")
        self.n_turno.setFont(font)
        self.primer_layout.addStretch()
        self.primer_layout.addWidget(self.numero_mayor)
        self.primer_layout.addStretch()
        self.primer_layout.addWidget(self.turno_anterior)
        self.primer_layout.addStretch()
        self.primer_layout.addWidget(self.n_turno)
        self.primer_layout.addSpacing(220)
        self.layout_general.addLayout(self.primer_layout)
        self.layout_general.addSpacing(50)
        ruta_foto_vacia = os.path.join(*self.parametros["RUTA_USER_PROFILE"])
        ruta_dado_tapado = os.path.join(*self.parametros["RUTA_DADO_TAPADO"])
        self.segundo_layout = QHBoxLayout()
        self.segundo_layout.addStretch()
        self.jugador_3 = QGridLayout()
        self.foto_jugador_3 = QLabel(self)
        self.foto_jugador_3.setFixedSize(60, 60)
        self.foto_jugador_3.setPixmap(QPixmap(ruta_foto_vacia).scaled(60, 60))
        self.jugador_3.addWidget(self.foto_jugador_3, 0, 0)
        self.vidas_3 = QLabel('Vidas: XXXX', self)
        self.vidas_3.setWordWrap(True)
        self.vidas_3.setStyleSheet("background-color: white;")
        self.vidas_3.setFixedSize(50, 50)
        self.jugador_3.addWidget(self.vidas_3, 0, 1)
        self.nombre_jugador_3 = QLabel(self.parametros['id_3'])
        self.nombre_jugador_3.setFont(font)
        self.nombre_jugador_3.setStyleSheet("color: white;")
        self.nombre_jugador_3.setFixedSize(140, 56)
        self.jugador_3.addWidget(self.nombre_jugador_3, 0, 2)
        self.jugador_3d1 = QLabel(self)
        self.jugador_3d1.setFixedSize(50, 50)
        self.jugador_3d1.setPixmap(QPixmap(ruta_dado_tapado).scaled(50, 50))
        self.jugador_3d2 = QLabel(self)
        self.jugador_3d2.setFixedSize(50, 50)
        self.jugador_3d2.setPixmap(QPixmap(ruta_dado_tapado).scaled(50, 50))
        self.jugador_3.addWidget(self.jugador_3d1, 1, 0)
        self.jugador_3.addWidget(self.jugador_3d2, 1, 1)
        self.segundo_layout.addLayout(self.jugador_3)
        self.segundo_layout.addStretch()
        self.layout_general.addLayout(self.segundo_layout)
        self.tercer_layout = QHBoxLayout()
        self.tercer_layout.addStretch()
        self.jugador_2 = QGridLayout()
        self.foto_jugador_2 = QLabel(self)
        self.foto_jugador_2.setFixedSize(60, 60)
        self.foto_jugador_2.setPixmap(QPixmap(ruta_foto_vacia).scaled(60, 60))
        self.jugador_2.addWidget(self.foto_jugador_2, 0, 0)
        self.vidas_2 = QLabel('Vidas: XXXX', self)
        self.vidas_2.setWordWrap(True)
        self.vidas_2.setStyleSheet("background-color: white;")
        self.vidas_2.setFixedSize(50, 50)
        self.jugador_2.addWidget(self.vidas_2, 0, 1)
        self.nombre_jugador_2 = QLabel(self.parametros['id_2'])
        self.nombre_jugador_2.setFont(font)
        self.nombre_jugador_2.setStyleSheet("color: white;")
        self.nombre_jugador_2.setFixedSize(140, 56)
        self.jugador_2.addWidget(self.nombre_jugador_2, 0, 2)
        self.jugador_2d1 = QLabel(self)
        self.jugador_2d1.setFixedSize(50, 50)
        self.jugador_2d1.setPixmap(QPixmap(ruta_dado_tapado).scaled(50, 50))
        self.jugador_2d2 = QLabel(self)
        self.jugador_2d2.setFixedSize(50, 50)
        self.jugador_2d2.setPixmap(QPixmap(ruta_dado_tapado).scaled(50, 50))
        self.jugador_2.addWidget(self.jugador_2d1, 1, 0)
        self.jugador_2.addWidget(self.jugador_2d2, 1, 1)
        self.tercer_layout.addLayout(self.jugador_2)
        self.tercer_layout.addSpacing(500)
        self.jugador_4 = QGridLayout()
        self.foto_jugador_4 = QLabel(self)
        self.foto_jugador_4.setFixedSize(60, 60)
        self.foto_jugador_4.setPixmap(QPixmap(ruta_foto_vacia).scaled(60, 60))
        self.jugador_4.addWidget(self.foto_jugador_4, 0, 0)
        self.vidas_4 = QLabel('Vidas: XXXX', self)
        self.vidas_4.setWordWrap(True)
        self.vidas_4.setStyleSheet("background-color: white;")
        self.vidas_4.setFixedSize(50, 50)
        self.jugador_4.addWidget(self.vidas_4, 0, 1)
        self.nombre_jugador_4 = QLabel(self.parametros['id_4'])
        self.nombre_jugador_4.setFont(font)
        self.nombre_jugador_4.setStyleSheet("color: white;")
        self.nombre_jugador_4.setFixedSize(140, 56)
        self.jugador_4.addWidget(self.nombre_jugador_4, 0, 2)
        self.jugador_4d1 = QLabel(self)
        self.jugador_4d1.setFixedSize(50, 50)
        self.jugador_4d1.setPixmap(QPixmap(ruta_dado_tapado).scaled(50, 50))
        self.jugador_4d2 = QLabel(self)
        self.jugador_4d2.setFixedSize(50, 50)
        self.jugador_4d2.setPixmap(QPixmap(ruta_dado_tapado).scaled(50, 50))
        self.jugador_4.addWidget(self.jugador_4d1, 1, 0)
        self.jugador_4.addWidget(self.jugador_4d2, 1, 1)
        self.tercer_layout.addLayout(self.jugador_4)
        self.tercer_layout.addStretch()
        self.layout_general.addSpacing(60)
        self.layout_general.addLayout(self.tercer_layout)
        self.cuarto_layout = QHBoxLayout()
        self.cuarto_layout.addStretch()
        self.turno_actual = QLabel('Turno de: Jimichael Butjordan', self)
        self.turno_actual.setStyleSheet("color: white;")
        self.turno_actual.setFont(font)
        self.turno_actual.setFixedSize(212, 112)
        self.cuarto_layout.addWidget(self.turno_actual)
        self.cuarto_layout.addStretch()
        self.jugador_1 = QGridLayout()
        self.foto_jugador_1 = QLabel(self)
        self.foto_jugador_1.setFixedSize(60, 60)
        self.foto_jugador_1.setPixmap(QPixmap(ruta_foto_vacia).scaled(60, 60))
        self.jugador_1.addWidget(self.foto_jugador_1, 0, 0)
        self.vidas_1 = QLabel('Vidas: XXXX', self)
        self.vidas_1.setWordWrap(True)
        self.vidas_1.setStyleSheet("background-color: white;")
        self.vidas_1.setFixedSize(50, 50)
        self.jugador_1.addWidget(self.vidas_1, 0, 1)
        self.nombre_jugador_1 = QLabel(self.parametros['id_1'])
        self.nombre_jugador_1.setFont(font)
        self.nombre_jugador_1.setStyleSheet("color: white;")
        self.nombre_jugador_1.setFixedSize(140, 56)
        self.jugador_1.addWidget(self.nombre_jugador_1, 0, 2)
        self.jugador_1d1 = QLabel(self)
        self.jugador_1d1.setFixedSize(50, 50)
        self.jugador_1d1.setPixmap(QPixmap(ruta_dado_tapado).scaled(50, 50))
        self.jugador_1d2 = QLabel(self)
        self.jugador_1d2.setFixedSize(50, 50)
        self.jugador_1d2.setPixmap(QPixmap(ruta_dado_tapado).scaled(50, 50))
        self.jugador_1.addWidget(self.jugador_1d1, 1, 0)
        self.jugador_1.addWidget(self.jugador_1d2, 1, 1)
        self.cuarto_layout.addLayout(self.jugador_1)
        self.cuarto_layout.addStretch()
        self.layout_botones = QGridLayout()
        self.boton_anunciar = QPushButton('ANUNCIAR VALOR', self)
        self.boton_pasar = QPushButton('PASAR TURNO', self)
        self.boton_cambiar = QPushButton('CAMBIAR DADOS', self)
        self.boton_poder = QPushButton('USAR PODER', self)
        self.boton_dudar = QPushButton('DUDAR', self)
        self.valor_anunciar = QLineEdit(self)
        self.valor_anunciar.setPlaceholderText("Ingrese valor aqui")
        self.layout_botones.addWidget(self.boton_anunciar, 0, 0)
        self.layout_botones.addWidget(self.valor_anunciar, 0, 1)
        self.layout_botones.addWidget(self.boton_pasar, 1, 0)
        self.layout_botones.addWidget(self.boton_cambiar, 1, 1)
        self.layout_botones.addWidget(self.boton_poder, 2, 0)
        self.layout_botones.addWidget(self.boton_dudar, 2, 1)
        self.cuarto_layout.addLayout(self.layout_botones)
        self.cuarto_layout.addSpacing(110)
        self.layout_general.addSpacing(90)
        self.layout_general.addLayout(self.cuarto_layout)
        self.layout_general.addSpacing(2000)
        self.setLayout(self.layout_general)
        self.dic_1 = {'nombre': self.nombre_jugador_1, 'vidas': self.vidas_1,
                      'd1': self.jugador_1d1, 'd2': self.jugador_1d2}
        self.dic_2 = {'nombre': self.nombre_jugador_2, 'vidas': self.vidas_2,
                      'd1': self.jugador_2d1, 'd2': self.jugador_2d2}
        self.dic_3 = {'nombre': self.nombre_jugador_3, 'vidas': self.vidas_3,
                      'd1': self.jugador_3d1, 'd2': self.jugador_3d2}
        self.dic_4 = {'nombre': self.nombre_jugador_4, 'vidas': self.vidas_4,
                      'd1': self.jugador_4d1, 'd2': self.jugador_4d2}

    def pop_up_error(self):
        pass

    def salir(self):
        self.close()

    def mostrar_ventana(self):
        self.show()

    def empezar(self):
        self.mostrar_ventana()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    ventana_Juego = VentanaJuego()
    sys.exit(app.exec())
